In [5]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, OneHotEncoder
from sklearn.compose import make_column_transformer

from sklearn.linear_model import LinearRegression, LogisticRegression
xcols1=["past_purchase_amt", "age","/blender.html","/cleats.html","/keyboard.html","/laptop.html","/tablet.html","gold","silver","bronze"]
xcols=["past_purchase_amt"]
model=LogisticRegression(fit_intercept=False,max_iter=1000) # a classifier, not a regressor, despite the name!


train_users = pd.read_csv("data/train_users.csv")
train_logs = pd.read_csv("data/train_logs.csv")
train_y = pd.read_csv("data/train_y.csv")

oh = OneHotEncoder()
data = oh.fit_transform(train_users[["badge"]])
data
frame=pd.DataFrame(data.toarray(), columns=oh.get_feature_names_out())



train_users["gold"]=frame["badge_gold"]
train_users["bronze"]=frame["badge_bronze"]
train_users["silver"]=frame["badge_silver"]


merged_inner = pd.merge(left=train_users, right=train_y)

In [6]:
merged_inner = pd.merge(left=train_users, right=train_y)


train_logs_final=train_logs.pivot_table(index="user_id",columns="url", values="seconds",aggfunc='sum')
train_logs_final.reset_index(level=0, inplace=True)

merged_final=merged_inner.merge(train_logs_final, how="left")
merged_final=merged_final.fillna(0)


model.fit(merged_final[xcols], merged_final["y"])

merged_final["prediction"] = model.predict(merged_final[xcols])


accuracy=(merged_final["y"] == merged_final["prediction"]).sum() / len(merged_final) * 100
accuracy

44.92666666666666

In [4]:
merged_final

,user_id,names,age,past_purchase_amt,badge,gold,bronze,silver,y,/blender.html,/cleats.html,/keyboard.html,/laptop.html,/tablet.html,prediction
0,0,Adriana Mcclure,26,39.344704,gold,1.0,0.0,0.0,False,15.0,0.0,170.0,142.0,0.0,True
1,1,Stacy Gilmore,67,15.840151,silver,0.0,0.0,1.0,False,0.0,0.0,78.0,0.0,0.0,False
2,2,Joanna Walsh,50,1099.420085,bronze,0.0,1.0,0.0,True,208.0,138.0,86.0,0.0,0.0,True
3,3,Eduardo Moore,65,5.880239,bronze,0.0,1.0,0.0,False,0.0,0.0,0.0,0.0,0.0,False
4,4,Angela Freeman,88,1312.296847,bronze,0.0,1.0,0.0,False,0.0,0.0,0.0,0.0,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29995,William Lewis,87,108.914205,bronze,0.0,1.0,0.0,False,0.0,0.0,171.0,392.0,0.0,True
29996,29996,James Miranda,49,291.969273,gold,1.0,0.0,0.0,True,116.0,169.0,0.0,0.0,247.0,True
29997,29997,Carlos Davis,46,2.609698,bronze,0.0,1.0,0.0,False,0.0,0.0,0.0,0.0,0.0,False
29998,29998,Makayla Smith,23,164.885894,bronze,0.0,1.0,0.0,False,0.0,0.0,0.0,0.0,0.0,False
29999,29999,Tina Anderson,51,161.905284,gold,1.0,0.0,0.0,True,111.0,147.0,65.0,120.0,24.0,True

In [ ]:
from sklearn.model_selection import train_test_split, cross_val_score


scores = cross_val_score(model, merged_final[xcols], train_y["y"])
print(f"AVG: {scores.mean()}, STD: {scores.std()}\n")

In [ ]:
merged_final["prediction"].to_numpy()

In [ ]:
from main import UserPredictor

In [ ]:

from main import UserPredictor
model = UserPredictor()
train_users = pd.read_csv("data/train_users.csv")
train_logs = pd.read_csv("data/train_logs.csv")
train_y = pd.read_csv("data/train_y.csv")
model.fit(train_users, train_logs, train_y)
test_users = pd.read_csv("data/test1_users.csv")
test_logs = pd.read_csv("data/test1_logs.csv")
y_pred = model.predict(test_users, test_logs)

y_pred

In [ ]:
!python3 tester.py